### ISSUE TITLE
How to set otf_num_processes

### ISSUE THREAD

**Issue by liujiqiangresearch** [facebookresearch/UnsupervisedMT#28]
Hi, it is not realistic to set otf_num_processes to 30 that is default  as many people are using the server . How do you set this parameter and what does it affect? Thank you,

**Comment by glample** [comment]
Each CPU job uses 2 threads. So if you have 24 CPU threads and one GPU on your server you probably want to set this value to 10, so that 20 CPU threads take care of generating back-parallel sentences, and the 4 remaining ones + the GPU take care of performing the actual training.

You ideally want to set this value high enough so that the GPU never has to wait for back-parallel sentences to be generated (otherwise this is time where the GPU is idle).

**Comment by liujiqiangresearch** [comment]
Ok, thank you very much.
