### ISSUE TITLE
how long does NMT model run on GPU's?

### ISSUE THREAD

**Issue by mohammedayub44** [facebookresearch/UnsupervisedMT#33]
Hi,

I'm trying to estimate cost for developing different models using this repo. Has anyone ran these experiments on multiple GPU's. How long should I expect the NMT model run for 1 GPU, 4 GPU and 8 GPU configs.

Any help appreciated
Cheers.

Mohammed Ayub

**Comment by glample** [comment]
Hi,

On 1 GPU it takes about 4 or 5 days to converge for En-Fr. But after 2 or 3 days the model is usually not very far from the final performance. It is not straightforward to make work on multi-GPU because the back-translation process (which for now generates back-parallel data on CPU threads) may slow down the training process a lot. In practice, the best in a multi-GPU setting would be to have some GPU generating back-parallel data, while some others perform the training, but we have not implemented this yet.

**Comment by mohammedayub44** [comment]
@glample Thanks for those insights. It helps.
How about timelines for different multi CPU's (1,4,16,32 etc) ?

**Comment by mohammedayub44** [comment]
Great Thanks @glample
