### ISSUE TITLE
How to deal with casing?

### ISSUE THREAD

**Issue by mayhewsw** [facebookresearch/UnsupervisedMT#62]
I'm trying to run the PBSMT model. As far as I can tell, run.sh doesn't deal with casing properly. The induced phrase-table is all lower-case, but the test text is never lower-cased, which means that many (upper-cased) words are untranslated. 

For example, I'm trying to reproduce the German-English results. "Flüchtlinge" is untranslated, but "flüchtlinge" is present in the phrase-table. This results in BLEU of 8.70 on newstest16. Lowercasing train and test only gets 13.33 BLEU. I tried retraining the LM on lowercased English, and this improved to 14.52.

Is there an additional step you did to get around this? Thanks!

**Comment by glample** [comment]
Hi,

We never use lowercasing, we use truecasing. See http://www.statmt.org/moses/?n=Moses.SupportTools#ntoc11 When you truecase a sentence, you only modify the first letter of the first word of the sentence.

For instance, if the sentence is: `This is the cat of Peter .` the truecaser will output: `this is the cat of Peter .` i.e. `Peter` remains unchanged since it is usually found with an uppercase in the corpus, but `this` will be lowercased since it usually is lowercased. This way, `Peter has a cat .` will remain unaffected by the truecaser.

So you indeed need to have uppercase in your phrase-table, which you will have if you trained your embeddings on truecased (or simply tokenized) data.

Unfortunately, the directory were we uploaded our embeddings was recently removed so I had to link to other embeddings: https://github.com/facebookresearch/UnsupervisedMT/commit/55169b48f6bc19b9ee5c13dbc67b11f191e6c540

But it turns out these are lowercased. I updated the links to new embeddings, not lowercased, it should fix your problem: https://github.com/facebookresearch/UnsupervisedMT/commit/b7e81ea457998560d336d12a613c3d9cf61efd6b

Thanks for noticing this!

**Comment by mayhewsw** [comment]
Thanks a lot! I'll try it out.

**Comment by mayhewsw** [comment]
These new embeddings work as advertised, but I'm still not able to get 15.63 BLEU on de-en newstest2016. My best score is 10.9.

Test data:
```
SRC_TEST=$PARA_PATH/dev/newstest2016-deen-src.de
TGT_TEST=$PARA_PATH/dev/newstest2016-deen-ref.en
```
These are my parameters:

```
Defined parameters (per moses.ini or switch):
        config: /home/mayhew/IdeaProjects/UnsupervisedMT/PBSMT/moses_train_de-en/model/moses.ini 
        distortion-limit: 6 
        feature: UnknownWordPenalty WordPenalty PhrasePenalty PhraseDictionaryMemory name=TranslationModel0 num-features=2 path=/home/mayhew/IdeaProjects/UnsupervisedMT/PBSMT/moses_train_de-en/model/phrase-table.gz input-factor=0 output-factor=0 Distortion KENLM name=LM0 factor=0 path=/home/mayhew/IdeaProjects/UnsupervisedMT/PBSMT/data/en.lm.blm order=5 
        input-factors: 0 
        mapping: 0 T 0 
        threads: 48 
        weight: UnknownWordPenalty0= 1 WordPenalty0= -1 PhrasePenalty0= 0.2 TranslationModel0= 0.2 0.2 Distortion0= 0.3 LM0= 0.5 
line=UnknownWordPenalty
FeatureFunction: UnknownWordPenalty0 start: 0 end: 0
line=WordPenalty
FeatureFunction: WordPenalty0 start: 1 end: 1
line=PhrasePenalty
FeatureFunction: PhrasePenalty0 start: 2 end: 2
line=PhraseDictionaryMemory name=TranslationModel0 num-features=2 path=/home/mayhew/IdeaProjects/UnsupervisedMT/PBSMT/moses_train_de-en/model/phrase-table.gz input-factor=0 output-factor=0
FeatureFunction: TranslationModel0 start: 3 end: 4
line=Distortion
FeatureFunction: Distortion0 start: 5 end: 5
line=KENLM name=LM0 factor=0 path=/home/mayhew/IdeaProjects/UnsupervisedMT/PBSMT/data/en.lm.blm order=5
```

Is there anything I'm missing? Happy to provide more info if it helps.
